services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./static/html:/usr/share/nginx/html